package com.sooware.med.model;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.upper_org
     *
     * @mbggenerated
     */
    private String upperOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.organizer
     *
     * @mbggenerated
     */
    private String organizer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.mag_way
     *
     * @mbggenerated
     */
    private String magWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.mag_level
     *
     * @mbggenerated
     */
    private String magLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.met_date
     *
     * @mbggenerated
     */
    private String metDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.met_addr
     *
     * @mbggenerated
     */
    private String metAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.at_time
     *
     * @mbggenerated
     */
    private Date atTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.app_id
     *
     * @return the value of article.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.app_id
     *
     * @param appId the value for article.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type
     *
     * @return the value of article.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type
     *
     * @param type the value for article.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.logo
     *
     * @return the value of article.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.logo
     *
     * @param logo the value for article.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.summary
     *
     * @return the value of article.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.summary
     *
     * @param summary the value for article.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.upper_org
     *
     * @return the value of article.upper_org
     *
     * @mbggenerated
     */
    public String getUpperOrg() {
        return upperOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.upper_org
     *
     * @param upperOrg the value for article.upper_org
     *
     * @mbggenerated
     */
    public void setUpperOrg(String upperOrg) {
        this.upperOrg = upperOrg == null ? null : upperOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.organizer
     *
     * @return the value of article.organizer
     *
     * @mbggenerated
     */
    public String getOrganizer() {
        return organizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.organizer
     *
     * @param organizer the value for article.organizer
     *
     * @mbggenerated
     */
    public void setOrganizer(String organizer) {
        this.organizer = organizer == null ? null : organizer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.mag_way
     *
     * @return the value of article.mag_way
     *
     * @mbggenerated
     */
    public String getMagWay() {
        return magWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.mag_way
     *
     * @param magWay the value for article.mag_way
     *
     * @mbggenerated
     */
    public void setMagWay(String magWay) {
        this.magWay = magWay == null ? null : magWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.mag_level
     *
     * @return the value of article.mag_level
     *
     * @mbggenerated
     */
    public String getMagLevel() {
        return magLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.mag_level
     *
     * @param magLevel the value for article.mag_level
     *
     * @mbggenerated
     */
    public void setMagLevel(String magLevel) {
        this.magLevel = magLevel == null ? null : magLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.met_date
     *
     * @return the value of article.met_date
     *
     * @mbggenerated
     */
    public String getMetDate() {
        return metDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.met_date
     *
     * @param metDate the value for article.met_date
     *
     * @mbggenerated
     */
    public void setMetDate(String metDate) {
        this.metDate = metDate == null ? null : metDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.met_addr
     *
     * @return the value of article.met_addr
     *
     * @mbggenerated
     */
    public String getMetAddr() {
        return metAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.met_addr
     *
     * @param metAddr the value for article.met_addr
     *
     * @mbggenerated
     */
    public void setMetAddr(String metAddr) {
        this.metAddr = metAddr == null ? null : metAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.at_time
     *
     * @return the value of article.at_time
     *
     * @mbggenerated
     */
    public Date getAtTime() {
        return atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.at_time
     *
     * @param atTime the value for article.at_time
     *
     * @mbggenerated
     */
    public void setAtTime(Date atTime) {
        this.atTime = atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Article other = (Article) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getLogo() == null ? other.getLogo() == null : this.getLogo().equals(other.getLogo()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getSummary() == null ? other.getSummary() == null : this.getSummary().equals(other.getSummary()))
            && (this.getUpperOrg() == null ? other.getUpperOrg() == null : this.getUpperOrg().equals(other.getUpperOrg()))
            && (this.getOrganizer() == null ? other.getOrganizer() == null : this.getOrganizer().equals(other.getOrganizer()))
            && (this.getMagWay() == null ? other.getMagWay() == null : this.getMagWay().equals(other.getMagWay()))
            && (this.getMagLevel() == null ? other.getMagLevel() == null : this.getMagLevel().equals(other.getMagLevel()))
            && (this.getMetDate() == null ? other.getMetDate() == null : this.getMetDate().equals(other.getMetDate()))
            && (this.getMetAddr() == null ? other.getMetAddr() == null : this.getMetAddr().equals(other.getMetAddr()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getAtTime() == null ? other.getAtTime() == null : this.getAtTime().equals(other.getAtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getLogo() == null) ? 0 : getLogo().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getSummary() == null) ? 0 : getSummary().hashCode());
        result = prime * result + ((getUpperOrg() == null) ? 0 : getUpperOrg().hashCode());
        result = prime * result + ((getOrganizer() == null) ? 0 : getOrganizer().hashCode());
        result = prime * result + ((getMagWay() == null) ? 0 : getMagWay().hashCode());
        result = prime * result + ((getMagLevel() == null) ? 0 : getMagLevel().hashCode());
        result = prime * result + ((getMetDate() == null) ? 0 : getMetDate().hashCode());
        result = prime * result + ((getMetAddr() == null) ? 0 : getMetAddr().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getAtTime() == null) ? 0 : getAtTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", type=").append(type);
        sb.append(", logo=").append(logo);
        sb.append(", title=").append(title);
        sb.append(", summary=").append(summary);
        sb.append(", upperOrg=").append(upperOrg);
        sb.append(", organizer=").append(organizer);
        sb.append(", magWay=").append(magWay);
        sb.append(", magLevel=").append(magLevel);
        sb.append(", metDate=").append(metDate);
        sb.append(", metAddr=").append(metAddr);
        sb.append(", content=").append(content);
        sb.append(", atTime=").append(atTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}