package com.sooware.med.model;

import java.io.Serializable;
import java.util.Date;

public class CaseRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.report
     *
     * @mbggenerated
     */
    private String report;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.at_date
     *
     * @mbggenerated
     */
    private Date atDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.hospital
     *
     * @mbggenerated
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.doctor_name
     *
     * @mbggenerated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_record.at_time
     *
     * @mbggenerated
     */
    private Date atTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.id
     *
     * @return the value of case_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.id
     *
     * @param id the value for case_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.user_id
     *
     * @return the value of case_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.user_id
     *
     * @param userId the value for case_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.description
     *
     * @return the value of case_record.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.description
     *
     * @param description the value for case_record.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.memo
     *
     * @return the value of case_record.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.memo
     *
     * @param memo the value for case_record.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.report
     *
     * @return the value of case_record.report
     *
     * @mbggenerated
     */
    public String getReport() {
        return report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.report
     *
     * @param report the value for case_record.report
     *
     * @mbggenerated
     */
    public void setReport(String report) {
        this.report = report == null ? null : report.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.result
     *
     * @return the value of case_record.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.result
     *
     * @param result the value for case_record.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.picture
     *
     * @return the value of case_record.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.picture
     *
     * @param picture the value for case_record.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.at_date
     *
     * @return the value of case_record.at_date
     *
     * @mbggenerated
     */
    public Date getAtDate() {
        return atDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.at_date
     *
     * @param atDate the value for case_record.at_date
     *
     * @mbggenerated
     */
    public void setAtDate(Date atDate) {
        this.atDate = atDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.hospital
     *
     * @return the value of case_record.hospital
     *
     * @mbggenerated
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.hospital
     *
     * @param hospital the value for case_record.hospital
     *
     * @mbggenerated
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.department
     *
     * @return the value of case_record.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.department
     *
     * @param department the value for case_record.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.doctor_name
     *
     * @return the value of case_record.doctor_name
     *
     * @mbggenerated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.doctor_name
     *
     * @param doctorName the value for case_record.doctor_name
     *
     * @mbggenerated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_record.at_time
     *
     * @return the value of case_record.at_time
     *
     * @mbggenerated
     */
    public Date getAtTime() {
        return atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_record.at_time
     *
     * @param atTime the value for case_record.at_time
     *
     * @mbggenerated
     */
    public void setAtTime(Date atTime) {
        this.atTime = atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CaseRecord other = (CaseRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getReport() == null ? other.getReport() == null : this.getReport().equals(other.getReport()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getPicture() == null ? other.getPicture() == null : this.getPicture().equals(other.getPicture()))
            && (this.getAtDate() == null ? other.getAtDate() == null : this.getAtDate().equals(other.getAtDate()))
            && (this.getHospital() == null ? other.getHospital() == null : this.getHospital().equals(other.getHospital()))
            && (this.getDepartment() == null ? other.getDepartment() == null : this.getDepartment().equals(other.getDepartment()))
            && (this.getDoctorName() == null ? other.getDoctorName() == null : this.getDoctorName().equals(other.getDoctorName()))
            && (this.getAtTime() == null ? other.getAtTime() == null : this.getAtTime().equals(other.getAtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getReport() == null) ? 0 : getReport().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
        result = prime * result + ((getAtDate() == null) ? 0 : getAtDate().hashCode());
        result = prime * result + ((getHospital() == null) ? 0 : getHospital().hashCode());
        result = prime * result + ((getDepartment() == null) ? 0 : getDepartment().hashCode());
        result = prime * result + ((getDoctorName() == null) ? 0 : getDoctorName().hashCode());
        result = prime * result + ((getAtTime() == null) ? 0 : getAtTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", description=").append(description);
        sb.append(", memo=").append(memo);
        sb.append(", report=").append(report);
        sb.append(", result=").append(result);
        sb.append(", picture=").append(picture);
        sb.append(", atDate=").append(atDate);
        sb.append(", hospital=").append(hospital);
        sb.append(", department=").append(department);
        sb.append(", doctorName=").append(doctorName);
        sb.append(", atTime=").append(atTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}