package com.sooware.med.model;

import java.io.Serializable;
import java.util.Date;

public class Fund implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.pay_id
     *
     * @mbggenerated
     */
    private String payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.pre_fee
     *
     * @mbggenerated
     */
    private Integer preFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.topup
     *
     * @mbggenerated
     */
    private Integer topup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.withdraw
     *
     * @mbggenerated
     */
    private Integer withdraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.at_time
     *
     * @mbggenerated
     */
    private Date atTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.id
     *
     * @return the value of fund.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.id
     *
     * @param id the value for fund.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.pay_id
     *
     * @return the value of fund.pay_id
     *
     * @mbggenerated
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.pay_id
     *
     * @param payId the value for fund.pay_id
     *
     * @mbggenerated
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.order_id
     *
     * @return the value of fund.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.order_id
     *
     * @param orderId the value for fund.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.pre_fee
     *
     * @return the value of fund.pre_fee
     *
     * @mbggenerated
     */
    public Integer getPreFee() {
        return preFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.pre_fee
     *
     * @param preFee the value for fund.pre_fee
     *
     * @mbggenerated
     */
    public void setPreFee(Integer preFee) {
        this.preFee = preFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.topup
     *
     * @return the value of fund.topup
     *
     * @mbggenerated
     */
    public Integer getTopup() {
        return topup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.topup
     *
     * @param topup the value for fund.topup
     *
     * @mbggenerated
     */
    public void setTopup(Integer topup) {
        this.topup = topup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.withdraw
     *
     * @return the value of fund.withdraw
     *
     * @mbggenerated
     */
    public Integer getWithdraw() {
        return withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.withdraw
     *
     * @param withdraw the value for fund.withdraw
     *
     * @mbggenerated
     */
    public void setWithdraw(Integer withdraw) {
        this.withdraw = withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.source
     *
     * @return the value of fund.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.source
     *
     * @param source the value for fund.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.at_time
     *
     * @return the value of fund.at_time
     *
     * @mbggenerated
     */
    public Date getAtTime() {
        return atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.at_time
     *
     * @param atTime the value for fund.at_time
     *
     * @mbggenerated
     */
    public void setAtTime(Date atTime) {
        this.atTime = atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Fund other = (Fund) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayId() == null ? other.getPayId() == null : this.getPayId().equals(other.getPayId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getPreFee() == null ? other.getPreFee() == null : this.getPreFee().equals(other.getPreFee()))
            && (this.getTopup() == null ? other.getTopup() == null : this.getTopup().equals(other.getTopup()))
            && (this.getWithdraw() == null ? other.getWithdraw() == null : this.getWithdraw().equals(other.getWithdraw()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getAtTime() == null ? other.getAtTime() == null : this.getAtTime().equals(other.getAtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayId() == null) ? 0 : getPayId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getPreFee() == null) ? 0 : getPreFee().hashCode());
        result = prime * result + ((getTopup() == null) ? 0 : getTopup().hashCode());
        result = prime * result + ((getWithdraw() == null) ? 0 : getWithdraw().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getAtTime() == null) ? 0 : getAtTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payId=").append(payId);
        sb.append(", orderId=").append(orderId);
        sb.append(", preFee=").append(preFee);
        sb.append(", topup=").append(topup);
        sb.append(", withdraw=").append(withdraw);
        sb.append(", source=").append(source);
        sb.append(", atTime=").append(atTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}