package com.sooware.med.model;

import java.io.Serializable;
import java.util.Date;

public class Mp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.app_secret
     *
     * @mbggenerated
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.app_token
     *
     * @mbggenerated
     */
    private String appToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.app_aesKey
     *
     * @mbggenerated
     */
    private String appAeskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.refresh_token
     *
     * @mbggenerated
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.raw_id
     *
     * @mbggenerated
     */
    private String rawId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.app_qr
     *
     * @mbggenerated
     */
    private String appQr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.service_type
     *
     * @mbggenerated
     */
    private Integer serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.verify_type
     *
     * @mbggenerated
     */
    private Integer verifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp.at_time
     *
     * @mbggenerated
     */
    private Date atTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.app_id
     *
     * @return the value of mp.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.app_id
     *
     * @param appId the value for mp.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.code
     *
     * @return the value of mp.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.code
     *
     * @param code the value for mp.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.name
     *
     * @return the value of mp.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.name
     *
     * @param name the value for mp.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.app_secret
     *
     * @return the value of mp.app_secret
     *
     * @mbggenerated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.app_secret
     *
     * @param appSecret the value for mp.app_secret
     *
     * @mbggenerated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.app_token
     *
     * @return the value of mp.app_token
     *
     * @mbggenerated
     */
    public String getAppToken() {
        return appToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.app_token
     *
     * @param appToken the value for mp.app_token
     *
     * @mbggenerated
     */
    public void setAppToken(String appToken) {
        this.appToken = appToken == null ? null : appToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.app_aesKey
     *
     * @return the value of mp.app_aesKey
     *
     * @mbggenerated
     */
    public String getAppAeskey() {
        return appAeskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.app_aesKey
     *
     * @param appAeskey the value for mp.app_aesKey
     *
     * @mbggenerated
     */
    public void setAppAeskey(String appAeskey) {
        this.appAeskey = appAeskey == null ? null : appAeskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.refresh_token
     *
     * @return the value of mp.refresh_token
     *
     * @mbggenerated
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.refresh_token
     *
     * @param refreshToken the value for mp.refresh_token
     *
     * @mbggenerated
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.raw_id
     *
     * @return the value of mp.raw_id
     *
     * @mbggenerated
     */
    public String getRawId() {
        return rawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.raw_id
     *
     * @param rawId the value for mp.raw_id
     *
     * @mbggenerated
     */
    public void setRawId(String rawId) {
        this.rawId = rawId == null ? null : rawId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.logo
     *
     * @return the value of mp.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.logo
     *
     * @param logo the value for mp.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.app_qr
     *
     * @return the value of mp.app_qr
     *
     * @mbggenerated
     */
    public String getAppQr() {
        return appQr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.app_qr
     *
     * @param appQr the value for mp.app_qr
     *
     * @mbggenerated
     */
    public void setAppQr(String appQr) {
        this.appQr = appQr == null ? null : appQr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.service_type
     *
     * @return the value of mp.service_type
     *
     * @mbggenerated
     */
    public Integer getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.service_type
     *
     * @param serviceType the value for mp.service_type
     *
     * @mbggenerated
     */
    public void setServiceType(Integer serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.verify_type
     *
     * @return the value of mp.verify_type
     *
     * @mbggenerated
     */
    public Integer getVerifyType() {
        return verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.verify_type
     *
     * @param verifyType the value for mp.verify_type
     *
     * @mbggenerated
     */
    public void setVerifyType(Integer verifyType) {
        this.verifyType = verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp.at_time
     *
     * @return the value of mp.at_time
     *
     * @mbggenerated
     */
    public Date getAtTime() {
        return atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp.at_time
     *
     * @param atTime the value for mp.at_time
     *
     * @mbggenerated
     */
    public void setAtTime(Date atTime) {
        this.atTime = atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Mp other = (Mp) that;
        return (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAppSecret() == null ? other.getAppSecret() == null : this.getAppSecret().equals(other.getAppSecret()))
            && (this.getAppToken() == null ? other.getAppToken() == null : this.getAppToken().equals(other.getAppToken()))
            && (this.getAppAeskey() == null ? other.getAppAeskey() == null : this.getAppAeskey().equals(other.getAppAeskey()))
            && (this.getRefreshToken() == null ? other.getRefreshToken() == null : this.getRefreshToken().equals(other.getRefreshToken()))
            && (this.getRawId() == null ? other.getRawId() == null : this.getRawId().equals(other.getRawId()))
            && (this.getLogo() == null ? other.getLogo() == null : this.getLogo().equals(other.getLogo()))
            && (this.getAppQr() == null ? other.getAppQr() == null : this.getAppQr().equals(other.getAppQr()))
            && (this.getServiceType() == null ? other.getServiceType() == null : this.getServiceType().equals(other.getServiceType()))
            && (this.getVerifyType() == null ? other.getVerifyType() == null : this.getVerifyType().equals(other.getVerifyType()))
            && (this.getAtTime() == null ? other.getAtTime() == null : this.getAtTime().equals(other.getAtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAppSecret() == null) ? 0 : getAppSecret().hashCode());
        result = prime * result + ((getAppToken() == null) ? 0 : getAppToken().hashCode());
        result = prime * result + ((getAppAeskey() == null) ? 0 : getAppAeskey().hashCode());
        result = prime * result + ((getRefreshToken() == null) ? 0 : getRefreshToken().hashCode());
        result = prime * result + ((getRawId() == null) ? 0 : getRawId().hashCode());
        result = prime * result + ((getLogo() == null) ? 0 : getLogo().hashCode());
        result = prime * result + ((getAppQr() == null) ? 0 : getAppQr().hashCode());
        result = prime * result + ((getServiceType() == null) ? 0 : getServiceType().hashCode());
        result = prime * result + ((getVerifyType() == null) ? 0 : getVerifyType().hashCode());
        result = prime * result + ((getAtTime() == null) ? 0 : getAtTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appId=").append(appId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", appSecret=").append(appSecret);
        sb.append(", appToken=").append(appToken);
        sb.append(", appAeskey=").append(appAeskey);
        sb.append(", refreshToken=").append(refreshToken);
        sb.append(", rawId=").append(rawId);
        sb.append(", logo=").append(logo);
        sb.append(", appQr=").append(appQr);
        sb.append(", serviceType=").append(serviceType);
        sb.append(", verifyType=").append(verifyType);
        sb.append(", atTime=").append(atTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}