package com.sooware.med.model;

import java.io.Serializable;
import java.util.Date;

public class ReserveSet extends ReserveSetKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_set.am
     *
     * @mbggenerated
     */
    private Integer am;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_set.pm
     *
     * @mbggenerated
     */
    private Integer pm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_set.max
     *
     * @mbggenerated
     */
    private Integer max;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_set.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_set.is_open
     *
     * @mbggenerated
     */
    private Integer isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_set.at_time
     *
     * @mbggenerated
     */
    private Date atTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_set.am
     *
     * @return the value of reserve_set.am
     *
     * @mbggenerated
     */
    public Integer getAm() {
        return am;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_set.am
     *
     * @param am the value for reserve_set.am
     *
     * @mbggenerated
     */
    public void setAm(Integer am) {
        this.am = am;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_set.pm
     *
     * @return the value of reserve_set.pm
     *
     * @mbggenerated
     */
    public Integer getPm() {
        return pm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_set.pm
     *
     * @param pm the value for reserve_set.pm
     *
     * @mbggenerated
     */
    public void setPm(Integer pm) {
        this.pm = pm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_set.max
     *
     * @return the value of reserve_set.max
     *
     * @mbggenerated
     */
    public Integer getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_set.max
     *
     * @param max the value for reserve_set.max
     *
     * @mbggenerated
     */
    public void setMax(Integer max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_set.price
     *
     * @return the value of reserve_set.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_set.price
     *
     * @param price the value for reserve_set.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_set.is_open
     *
     * @return the value of reserve_set.is_open
     *
     * @mbggenerated
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_set.is_open
     *
     * @param isOpen the value for reserve_set.is_open
     *
     * @mbggenerated
     */
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_set.at_time
     *
     * @return the value of reserve_set.at_time
     *
     * @mbggenerated
     */
    public Date getAtTime() {
        return atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_set.at_time
     *
     * @param atTime the value for reserve_set.at_time
     *
     * @mbggenerated
     */
    public void setAtTime(Date atTime) {
        this.atTime = atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ReserveSet other = (ReserveSet) that;
        return (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getWeek() == null ? other.getWeek() == null : this.getWeek().equals(other.getWeek()))
            && (this.getAm() == null ? other.getAm() == null : this.getAm().equals(other.getAm()))
            && (this.getPm() == null ? other.getPm() == null : this.getPm().equals(other.getPm()))
            && (this.getMax() == null ? other.getMax() == null : this.getMax().equals(other.getMax()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getIsOpen() == null ? other.getIsOpen() == null : this.getIsOpen().equals(other.getIsOpen()))
            && (this.getAtTime() == null ? other.getAtTime() == null : this.getAtTime().equals(other.getAtTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getWeek() == null) ? 0 : getWeek().hashCode());
        result = prime * result + ((getAm() == null) ? 0 : getAm().hashCode());
        result = prime * result + ((getPm() == null) ? 0 : getPm().hashCode());
        result = prime * result + ((getMax() == null) ? 0 : getMax().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getIsOpen() == null) ? 0 : getIsOpen().hashCode());
        result = prime * result + ((getAtTime() == null) ? 0 : getAtTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", am=").append(am);
        sb.append(", pm=").append(pm);
        sb.append(", max=").append(max);
        sb.append(", price=").append(price);
        sb.append(", isOpen=").append(isOpen);
        sb.append(", atTime=").append(atTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}