package com.sooware.med.dao;

import com.sooware.med.model.CaseRecord;

public interface CaseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    int insert(CaseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    int insertSelective(CaseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    CaseRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CaseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CaseRecord record);

	CaseRecord selectByUsrId(String userId);
}