package com.sooware.med.dao;

import com.sooware.med.bean.BizQuery;
import com.sooware.med.model.MpBody;

public interface MpBodyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_body
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_body
     *
     * @mbggenerated
     */
    int insert(MpBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_body
     *
     * @mbggenerated
     */
    int insertSelective(MpBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_body
     *
     * @mbggenerated
     */
    MpBody selectByPrimaryKey(String appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_body
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MpBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_body
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MpBody record);

	BizQuery selectDoctor(BizQuery record);

	BizQuery insertByArticle(BizQuery record);

	BizQuery updateByDoctor(BizQuery record);
}