package com.sooware.med.dao;

import com.sooware.med.model.Mp;

public interface MpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    int insert(Mp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    int insertSelective(Mp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    Mp selectByPrimaryKey(String appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mp record);
}