package com.sooware.med.dao;

import java.util.List;

import com.sooware.med.bean.BizQuery;
import com.sooware.med.model.MpUser;
import com.sooware.med.model.MpUserKey;

public interface MpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MpUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    int insert(MpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    int insertSelective(MpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    MpUser selectByPrimaryKey(MpUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MpUser record);

	List<BizQuery> selectPatient(BizQuery record);
}