package com.sooware.med.dao;

import java.util.List;

import com.sooware.med.model.Reserve;
import com.sooware.med.model.ReserveKey;

public interface ReserveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ReserveKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated
     */
    int insert(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated
     */
    int insertSelective(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated
     */
    Reserve selectByPrimaryKey(ReserveKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Reserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reserve record);

	List<Reserve> selectByWeek(Integer week);

	Integer countByWeek(Integer week);

	Integer countByAll(Reserve reserveInfo);
}