package com.sooware.med.dao;

import com.sooware.med.model.ReserveSet;
import com.sooware.med.model.ReserveSetKey;

public interface ReserveSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ReserveSetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    int insert(ReserveSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    int insertSelective(ReserveSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    ReserveSet selectByPrimaryKey(ReserveSetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReserveSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReserveSet record);
}